### ISSUE TITLE
CapsulaHub repositories

### ISSUE THREAD

**Issue by stephanebenayoun** [capsulajs/capsulajs#22]
## Proposition

We need to define how we want to organise our core services, services, components and UI components in repositories.

The proposition is to have 3 mono-repositories (using lerna) :
- **capsulahub-core** for core services of capsulahub.
Example: Workspace, Orchestrator, Layout, etc.
- **capsulahub-extensions** for all the elements especially built for capsulahub and that the Workspace will be able to load (services and components).
Example: Selector service, Catalog component, etc.  
- **capsulahub-ui** for all simple reusable UI components
Example: Button, dropdown, etc.

Services that are completely independent (like EnvRegistry) can stay in a separate repository.

### Goals/Values

The goal is to define a clear structure and to be able to quickly create new elements for CapsulaHub.

### RoadMap

1. For **each repository** (capsulahub-core, capsulahub-extensions, capsulahub-ui):
- Create the repository and apply correct github settings
- Init the repo with Lerna and configure it
- Configure CI/CD
- Add README to the repository
- Define standard package and create template for it

2. Migrate existing packages from other repositories in the corresponding new repository (if needed make them matching with the repo standard for packages)

### Definition of Done

- [ ] Relevant issues have been created

**Comment by MikeSquall** [comment]
Looks good to me.

**Comment by 95kach** [comment]
1) For `capsulahub-ui` I suggest using one repo without Lerna,  because I don't see the profit of creation a separate package for 3 line component `button` or `span`.

2) We are using `capsulahub-ui` just for base off the web component, importing only one component from the `capsulahub-ui` we will not include all of the components inside the `web-component-button` (example).

So my conclusion it's redundant.

Or another solution replace `capsulahub-ui` and `capsulahub-ui-web-components` by just one repository.

Without these multiple imports of monorepositories inside monorepositories.

Because for now, we have `capsulahub-ui` and `capsulahub-ui-web-components`.
And web components it's the only wrapper of usual component.
So for me, it's better to replace it with one repo. In that case, I agree that it should be mono repo with Larna.

**Comment by idanilt** [comment]
capsulahub-ui-web-components should be in extensions, p.s. the name is bad
capsulahub-ui can be single package, just make sure tree shaking in enabled

**Comment by dmitriyslaym** [comment]
As I understand, we will not have **web-components** repo at all anymore, web-components will be included in **capsulahub-extensions** repo (each component will be a separate lerna package). Is it correct, @stephanebenayoun ?
I also agree that there is no need to split **capsulahub-ui** to multiple lerna packages.

**Comment by stephanebenayoun** [comment]
> As I understand, we will not have **web-components** repo at all anymore, web-components will be included in **capsulahub-extensions** repo (each component will be a separate lerna package). Is it correct, @stephanebenayoun ?

Yes it's correct, we will have all extensions in **capsulahub-extensions**

**Comment by dmitriyslaym** [comment]
@stephanebenayoun I would suggest to take capsula-ui repository and put it is a separate package in **capsulahub-extensions**. It's highly inconvenient to keep ui-components in a separate repository and I don't see a benefit in it. When I was working on Web-component task, I had to create lots of PRs to ui repo in order to provide some improvements. If we keep UI package in capsulahub-extensions, we still will have it kind of independent, but it will be much easier to make changes there.
